spring.application.name=job-recommendation-graph

# Use cognodb.com (NOT cognodb.cloud)

spring.neo4j.uri=${COGNODB_URI:bolt+s://db-f8989861.databases.cognodb.com:7687}
spring.neo4j.authentication.username=${COGNODB_USER:admin}
spring.neo4j.authentication.password=${COGNODB_PASSWORD:23a5a2b876560a901c5f1f0e5890ba4b}

# SpringDoc OpenAPI & Swagger UI Configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method